name: testcheckrunner


on:
  workflow_dispatch:


jobs:
  job1:
    runs-on: [ self-hosted, test-label ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: CAT TXT
        run: cat test3.txt
